<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="1" failures="1" errors="0" time="0.296">
    <testsuite name="tests/functions/handlers.spec.ts" timestamp="2025-08-27T08:00:24.832Z" hostname="Iluvatar" tests="1" failures="1" errors="0" skipped="0" time="0">
        <testcase classname="tests/functions/handlers.spec.ts" name="tests/functions/handlers.spec.ts" time="0">
            <failure message="Failed to load url cloudflare:test-internal (resolved id: cloudflare:test-internal) in cloudflare:test-a9f7771f-07db-4031-8ab0-0a09f6e3ffe8. Does the file exist?" type="Error">
Error: Failed to load url cloudflare:test-internal (resolved id: cloudflare:test-internal) in cloudflare:test-a9f7771f-07db-4031-8ab0-0a09f6e3ffe8. Does the file exist?
 ‚ùØ loadAndTransform node_modules/.pnpm/vite@5.4.19_@types+node@20.19.11/node_modules/vite/dist/node/chunks/dep-C6uTJdX2.js:51968:17

            </failure>
        </testcase>
    </testsuite>
</testsuites>
